Added Quora Support
jordwest/news-feed-eradicator pull request #146
Opened 2021-07-15 09:16 UTC by DivyanshByte

Quora Support

Issue: #122

2021-08-10 09:59 UTC, jordwest requested changes
Amazing, thank you!

Can you please remove the diff for `package-lock.json`?

2021-08-10 09:59 UTC, jordwest commented on src/sites/quora.ts
> +			// document.body.style.background = 'var(--yt-spec-general-background-a)';
Can this comment be removed? Looks like copypasta

2021-08-10 16:45 UTC, DivyanshByte commented on src/sites/quora.ts
> +			// document.body.style.background = 'var(--yt-spec-general-background-a)';
yeah I Just Copied From Youtube One and Modified it :) I will Just Remove It No Problem

2022-02-06 04:23 UTC, closed without merging

2022-06-22 00:53 UTC, noethig commented
What happend to this PR? I don't see any settings in the newsFeedEradicator and the newsfeed is not blocked on Quora...